language: node_js
dist: trusty
node_js: stable
before_script:
- npm install --silent bower polymer-cli
- ./node_modules/.bin/bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- ./node_modules/.bin/polymer test --plugin sauce --job-name "environment-selector:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: b4vM5TikPME5cJvzn4alFJ6O3vrZyIvc7SYZq8wfxouzbn1XB4gQt76+stCDxVPpphaE9VEuKtQ+xEcHZqxnzmAJCDzTRROhTJFV95wLFGyBTa4A5malxe6/77fHHD6Le1DJ86AY8ArUkvjXmjCRz00ZbfRQH14ZXFNNK55vTiFjb1Z71ARiJdN5PNDhZ79y0ZzxqUxxwUcq2bFfJ3mD6tnA7FEpq0IXK8cTCatXkaNUQowI8D1v9ehoTp5CMJcINZAw/UPDRDAwaEyK5WZ4Pp5VNEsjNVpKV6FvtorZYF37+nii9FE+sZvOj9hHnzaBR4waKan8XzJdqWvBlnopYAdPi4+Xv8RFhRT3snOkAthBUjRvflV+b3trlRlCcVzDoErQKpLOU8/KEObffKMtjF5y3HoJM48NdC+b2R1UKlbkmu0dD7as96bBspzkBBS9lnnNRqm80DN5FH/xHNUTxffIWzSQhJcpS3C/4NEdePQXYNusIjwXNT25e2mu+/rTOjaiKRPj98mfWmQElzBhul8jD9EybYhXUfkPTQ8skGdqsMgOPCUYmLCNzatpp1Q4E1d++CZ2TUHsVo6OXeVR3xLtO0776qkuze+ACCmxtyXT7jaIOdui3V3Oe/nrcW1JloiCavqGBCBqeW8/htfTMIRqxFWEyBexbW0XDTwLBVw=
  - secure: cB8fmvPsuZAQZKffJSJNjLBj6gmkKq5DO85G8O+eR7n66J7Tr93stVn0TzR6gG9IK+SCmvKiIgdV+/ReA+ksN1fMdvuEe0RT52Eem9qi1X0qXF4YkmgYCy40HSu5gtqUELRsIFfbjpEVuvwzFVsbP9vS2W9Ywh4fo6IzfhCqqV8Te4GH651sdaeqmaA0JwMXfLU8E1dW4xYadsxRogUP5IWcpnDPcS88Y6E7jBn0uVUp6Pi2r+PQQKe9lM7YJKjAC76pe4BTDszWZG9ED+Z3DK5ITGvUmixE22pgPI/h65SQTPrWluD5PhckoWCLMS9MuYRQl4WSBaf+M1EPov6X53hFtDj4eEoWxia09SHxViajg/akFdOX+rxvWvu6uxyUxvj/ahtCgKBtGQ1a2zQFMk9cW9IC0irYBSBTgDS5nyGWbyJnzgTaMacqRru0HPpQ+WB5+c37Owuf3KQ9jQa6AhSeSRE4/5yzqYzEFiVBzO6+yq4SKZCGWKpfpUMoFvamZR8JHcBDEq65V2vQjLsxSN2hZ8OYyyUarmhZeHYLGzSE6ar75KzXXrcfcbLEg0IOVePOp0K6fX9tk2e8hhs050XFKW3pXh1CEemwHKSJFTcPb2mwkH3WBBQyF5rl8WaO6lZbBJb3Hb5AqvJXCu/E2Zdnzhh7zriihJGrHLHslaE=
  - secure: VgilGBe9Nnjmepar7L0z5rMBHpwQJjQCGFwK5CsPTRIUqhlnJju6pv8tm7GR3w/SIrYgFLbQXoJ/tXuzqcUJu9NNuKyVZDpe1Gulz1pDnK/SuQGuLDpswXPcblhZVc6v9FohSc8nEdTOwPGQMYf/FsvmFRk9VESTXADk6Ng3/Dp3H3B+K0b0r/+MwjAFi1v8mJRbK/Mim/6iXiPR9RHMtWOYVjNDWoTUjQ4jBlVLgxNTKbDuf6DMlAyLVjjJ6s+MhvoHWFMEOwTmhmHn+ITBkISZpNf4/OYhkNTEn3SnhZRWOkjXO4EoKRhQTCLPPALUZCu4xV+rBYKPNv9mvs/Fx1OR1bHtJC92yrs11zBwYniQpPli0N3ewGYrLAdbkVQzdyV3ELf/Lipzo48qJQft8INzcSBkGi+9ggaOkU9lLaPh/sdOiW5wQfbrju+yReFln0OnxQu/MSO8ZQ/kK2qm+ER6KGJRbcbLzQHcG+pBEB+yMQgEqplE6ALVauPC4pFvyEm7F0ZA8MyKwUSbdPK2eVdbZkCFt0LFNESJ4yY9h2+Y7p3qAnbnXzjG2daTXm03c3JROx3ue8ehF8wk2E5WCa4eJEIsJnZ6+RmUyIqiL8JXsxZPqC8A2DTSA69TuI2TKn73d6yq9oYL2YIl6jKYilSlMCuZgxnNluzudWJDkAc=
