/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   environment-selector.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace UiElements {

  /**
   * An element to select current variables environment.
   *
   * Renders a material design dropdown with list of available environments.
   * It always render environment **Default** (value `default`).
   *
   * ### Example
   *
   * ```html
   * <environment-selector></environment-selector>
   * ```
   *
   * ```javascript
   * document.queryElement('environment-selector')
   * .addEventListener('selected-environment-changed', (e) => {
   *    console.log(e.detail.value); // Selected environment
   * });
   * ```
   *
   * ### Styling
   *
   * Use variables for `paper-dropdown-menu`, `paper-listbox` and `paper-item`
   * to style the control.
   */
  class EnvironmentSelector extends
    VariablesConsumerMixin(
    Object) {

    /**
     * Set to make selector's label dissapear after selection has been made.
     */
    noLabelFloat: boolean|null|undefined;

    /**
     * Selected environment.
     */
    selected: string|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;

    /**
     * Handler for the `selected-environment-changed` event.
     */
    _envChangedHandler(e: CustomEvent|null): void;

    /**
     * Handler for the `selected` property change
     */
    _environmentChanged(selected: String|null): void;

    /**
     * Dispatches `selected-environment-changed` custom event
     *
     * @param value New value
     * @returns Dispatched event
     */
    _dispatchChange(value: String|null): CustomEvent|null;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "environment-selector": UiElements.EnvironmentSelector;
  }
}

export {};
